### ISSUE TITLE
Transaction tracker

### ISSUE THREAD

**Issue by 7alip** [solangegueiros/rsk.academy#17]
It might be nice feature to have a transaction tracker and notifier feature.

- [ ] Consider of storing transaction history in storage.
- [x] Notify user when transaction is successfully mined or failed.
- [x] Create a component for viewing the current transactions and history

**Comment by 7alip** [comment]
Persist transaction feature will be implemented with #58
